config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'posts#index'

	resources :posts do
		resources :comments, only: [:create, :destroy]
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  validates :comment, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	belongs_to :user

	validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :comments

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
  	@comment = @post.comments.create(comment_params)

  	redirect_to post_path(@post)
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

  	redirect_to post_path(@post)
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end

  def comment_params
  	params.require(:comment).permit(:comment).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, except: [:index, :new, :create]

	def index
		@posts = Post.all
	end

	def new
		@post = Post.new
	end

	def create
		@post = current_user.posts.build(post_params)
		if @post.save
			redirect_to post_path(@post)
		else
			render :new
		end
	end

	def show
		@comment = Comment.new
	end

	def edit; end

	def update
		if @post.update(post_params)
			redirect_to post_path(@post)
		else
			render :edit
		end
	end

	def destroy
		@post.destroy

		redirect_to posts_path
	end

	private

	def set_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :content)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Blog E-info', root_path, class: 'navbar-item' %>
            </div>
            <div id="navbarMenuHeroA" class="navbar-menu">
              <div class="navbar-end">
                <%= link_to 'Criar nova postagem',
                            new_post_path,
                            class: 'navbar-item' %>
                <%= link_to 'Sair',
                            destroy_user_session_path,
                            class: 'navbar-item',
                            method: :delete %>
              </div>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield(:page_title) %>
          </h1>
          <h3 class="subtitle">
            <%= yield(:page_subtitle) %>
          </h3>
        </div>
      </div>
    </section>

    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <section class="hero is-primary is-medium">
      <div class="hero-head">
        <nav class="navbar">
          <div class="container">
            <div class="navbar-brand">
              <%= link_to 'Blog E-info', root_path, class: 'navbar-item' %>
            </div>
          </div>
        </nav>
      </div>

      <div class="hero-body">
        <div class="container has-text-centered">
          <h1 class="title">
            <%= yield(:page_title) %>
          </h1>
          <h3 class="subtitle">
            <%= yield(:page_subtitle) %>
          </h3>
        </div>
      </div>
    </section>

    <%= yield %>
  </body>
</html>

app/views/posts/_comment_form.html.erb
<%= simple_form_for @comment, url: post_comments_path(@post) do |f| %>
	<div class="field">
		<%= f.input :comment, 
					label: 'Comentário',
		            input_html: { class: 'textarea' }, 
		            wrapper: false, 
		            label_html: { class: 'label' } %>
	</div>

	<%= f.submit 'Enviar comentário', class: 'button is-primary' %>
<% end %>

app/views/posts/_comments.html.erb
<% @post.comments.each do |comment| %>
	<div class="box">
		<div class="media">
			<div class="media-content">
				<p>
					<strong><%= comment.user.email %>:</strong>
					<%= comment.comment %>
				</p>
			</div>

			<% if comment.user == current_user %>
				<%= link_to 'Deletar',
				            post_comment_path(@post, comment),
				            class: 'button is-danger',
				            method: :delete,
				            data: { confirm: 'Tem certeza?' } %>
			<% end %>
		</div>
	</div>
<% end %>

app/views/posts/_form.html.erb
<div class="section">
	<div class="container">
		<%= simple_form_for @post do |f| %>
			<div class="field">
				<%= f.input :title,
							label: 'Título',
				            input_html: { class: 'input' }, 
							wrapper: false, 
							label_html: { class: 'label' } %>
			</div>
			<div class="field">
				<%= f.input :content, 
							label: 'Conteúdo',
				            input_html: { class: 'textarea' }, 
				            wrapper: false, 
				            label_html: { class: 'label' } %>
			</div>

			<%= f.submit 'Salvar postagem', class: 'button is-primary' %>
		<% end %>
	</div>
</div>

app/views/posts/edit.html.erb
<% content_for(:page_title, 'Editar postagem') %>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= content_for(:page_title, 'Lista de postagens') %>

<div class="section">
	<div class="container">
		<% @posts.each do |post| %>
			<div class="card">
				<div class="card-content">
					<p class="title">
						<%= link_to post.title, post_path(post) %>
					</p>
					<div class="subtitle is-6">
						<%= post.user.email %>
					</div>
					<div class="comment-count">
						<span class="tag is-rouded">
							<%= post.comments.count %> comentário(s)
						</span>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/posts/new.html.erb
<%= content_for(:page_title, 'Nova postagem') %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for(:page_title, @post.title) %>
<% content_for(:page_subtitle, @post.user.email) %>

<div class="section">
	<div class="container">
		<% if @post.user == current_user %>
			<div class="level">
				<div class="level-left">
					<p class="level-item"><strong>Ações</strong></p>
				</div>
				<div class="level-right">
					<div class="level-item">
						<%= link_to 'Editar',
						            edit_post_path(@post),
						            class: 'button is-primary' %>
					</div>
					<div class="level-item">
						<%= link_to 'Deletar',
							post_path(@post),
							class: 'button is-danger',
							method: :delete,
							data: { confirm: 'Você tem certeza?' } %>
					</div>
				</div>
			</div>
		<% end %>
	</div>
</div>

<div class="section">
	<div class="container">
		<div class="content">
			<%= simple_format @post.content %>
		</div>
	</div>
</div>

<div class="section">
	<div class="container">
		<h5 class="subtitle is-5">
			<strong><%= @post.comments.count %></strong> Comentário(s)
		</h5>

		<%= render 'comments' %>

		<hr />

		<h3 class="subtitle is-3">Deixe um comentário!</h3>

		<%= render 'comment_form' %>
	</div>
</div>